### ISSUE TITLE
Automatic Import

### ISSUE THREAD

**Issue by Integraluminium** [ScreepCode/DHBW-Programmieren-Vorlesung#5]
Hi,
vielen Dank für deine bereitgestellten Templates.
Zu den Live Templates, wäre mein Vorschlag noch die genauen Pfade der Java Pakete hinzuzufügen.
IntelliJ importiert daraufhin automatisch die Pakete und verringert somit den Aufwand des manuellen Importierens.
Falls die Idee gefällt, kannst du diese umsetzten, falls nicht kannst du diesen Vorschlag löschen.

**Comment by ScreepCode** [comment]
Hey, 
mich hat das bisher auch ein wenig genervt. Ich wusste nicht das es so einfach geht :)
Die Änderungen sollten alle in dem PR mit dem Commit drin sein und einmal überarbeitet sein ^^
